// client/src/pages/LogIn/index.jsx
import React from "react";

const index = () => {
  return (
    <div className="container">
      <div className="container_formulario">
        <div className="icono_1">
          <i className="fa-solid fa-user"></i>
        </div>
        <input type="text" className="login" placeholder="Usuario" />
        <input type="password" className="login" placeholder="contraseña" />
        <button className="btn">Iniciar Sesion</button>
        <a href="#" className="forgot">
          Olvidaste tu contraseña?
        </a>

        <div className="card">
          <div className="text_card">
            <p>Visita nuestra</p>
            <p>pagina</p>
            <p>principal!</p>
          </div>

          <div className="img_card">
            <i className="fa-solid fa-graduation-cap"></i>
          </div>
        </div>
      </div>

      <div className="container_img">
        <img src="../../assets/chinos.png" alt="" />
      </div>
    </div>
  );
};

export default index;

// students/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
    console.log("esta mierda funciona")
  }

}

<div class="container">
    <div class="container_formulario">
        <div class="icono_1"><i class="fa-solid fa-user"></i></div>
        <input type="text" class="login" placeholder="Usuario">
        <input type="password" class="login" placeholder="contraseña">
        <button class="btn">Iniciar Sesion</button>
        <a href="#" class="forgot">Olvidaste tu contraseña?</a>

        <div class="card">
            <div class="text_card">
                <p>Visita nuestra</p>
                <p>pagina</p>
                <p>principal!</p>
            </div>

            <div class="img_card"><i class="fa-solid fa-graduation-cap"></i></div>
        </div>

    </div>


    <div class="container_img">
        <img src="../../assets/chinos.png" alt="">
    </div>
</div>
